name: Promote Release to Latest

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to promote to latest (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  retag-as-latest:
    name: Retag Images as Latest
    runs-on: ubuntu-latest
    
    steps:
      - name: Validate release exists
        run: |
          RELEASE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ inputs.release_tag }}")
          
          if [ "$(echo $RELEASE | jq -r '.message')" = "Not Found" ]; then
            echo "Release ${{ inputs.release_tag }} not found"
            exit 1
          fi
          
          echo "Release found: ${{ inputs.release_tag }}"
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pull and retag Server image (GHCR)
        run: |
          docker pull ghcr.io/${{ github.repository }}/server:${{ inputs.release_tag }}
          docker tag ghcr.io/${{ github.repository }}/server:${{ inputs.release_tag }} ghcr.io/${{ github.repository }}/server:latest
          docker push ghcr.io/${{ github.repository }}/server:latest

      - name: Pull and retag Daemon image (GHCR)
        run: |
          docker pull ghcr.io/${{ github.repository }}/daemon:${{ inputs.release_tag }}
          docker tag ghcr.io/${{ github.repository }}/daemon:${{ inputs.release_tag }} ghcr.io/${{ github.repository }}/daemon:latest
          docker push ghcr.io/${{ github.repository }}/daemon:latest